### ISSUE TITLE
Pre-0.8 audit

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#1692]
- [x] Audit top-level crate docs
- [x] Audit top-level traits
  - [x] `KnownLayout`
  - [x] `Immutable`
  - [x] `Unaligned`
  - [x] `TryFromBytes`
  - [x] `FromZeros`
  - [x] `FromBytes`
  - [x] `IntoBytes`
- [x] Audit `byte_slice` module docs and traits: #1700
  - [x] `ByteSlice`
  - [x] `ByteSliceMut`
  - [x] `CloneableByteSlice`
  - [x] `CopyableByteSlice`
  - [x] `IntoByteSlice`
  - [x] `IntoByteSliceMut`
  - [x] `SplitByteSlice`
  - [x] `SplitByteSliceMut`
- [x] Audit `Ref` module docs and type: #1706
  - [x] `Ref` methods which PME for ZST DSTs should document this behavior
  - [x] `Ref` should document its intended use cases
- [x] Audit macros
  - [x] `transmute!`
  - [x] `transmute_ref!`
  - [x] `transmute_mut!`
  - [x] `try_transmute!`
  - [x] `try_transmute_ref!`
  - [x] `try_transmute_mut!`
  - [x] `include_value!`
- [x] Audit `byteorder` module: #1707
  - [x] seal `ByteOrder` trait: #1698
- [x] Audit `error` module: #1704
- [x] Audit `Unalign`: #1701
